# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "rust_kvs",
    actual = "//score/kvs_rust:kvs_rust",
    deprecation = "//score/kvs/rust_kvs:rust_kvs has moved to //score/kvs_rust:kvs_rust. " +
                  "Update your dependency to the new //score/... label.",
    visibility = ["//visibility:public"],
)
